// USER REDUCER

export const ADD_USER_DETAILS = "ADD_USER_DETAILS";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";

// PRODUCTS REDUCER

export const FETCH_PRODUCTS_STARTED = "FETCH_PRODUCTS_STARTED";
export const FETCH_PRODUCTS_FINISHED = "FETCH_PRODUCTS_FINISHED";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

// CART REDUCER

export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";

// CART REDUCER

export const FETCH_PRODUCT_STARTED = "FETCH_PRODUCT_STARTED";
export const FETCH_PRODUCT_FINISHED = "FETCH_PRODUCT_FINISHED";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

