// USER REDUCER

export const ADD_USER_DETAILS = "ADD_USER_DETAILS";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";

// PRODUCTS REDUCER

export const FETCH_PRODUCTS_STARTED = "FETCH_PRODUCTS_STARTED";
export const FETCH_PRODUCTS_FINISHED = "FETCH_PRODUCTS_FINISHED";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

// CART REDUCER

export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";

// PRODUCT REDUCER

export const FETCH_PRODUCT_STARTED = "FETCH_PRODUCT_STARTED";
export const FETCH_PRODUCT_FINISHED = "FETCH_PRODUCT_FINISHED";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

// USERS REDUCER

export const FETCH_USERS_STARTED = "FETCH_USERS_STARTED";
export const FETCH_USERS_FINISHED = "FETCH_USERS_FINISHED";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

// ERROR REDUCER

export const ERROR_THROWN = "ERROR_THROWN";
export const ERROR_DISMISSED = "ERROR_DISSMISED";
export const ERROR_NULL = "ERROR_NULL";

